version: 0.2

env:
  variables:
APP_ENV: stage
  parameter-store:
    DB_HOST: "/app/${APP_ENV}/db_host"
    API_URL: "/app/${APP_ENV}/api_url"
    LOG_LEVEL: "/app/${APP_ENV}/log_level"

phases:
  build:
    commands:
      - echo "Environment is $APP_ENV"
      - ./app.sh
